name: Release genrepass-cli
on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  preparations:
    name: Preparations
    runs-on: ubuntu-20.04
    steps:
      - name: Create release version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract release title
        run: |
          title=$(grep "## \[${{ env.RELEASE_VERSION }}\]" CHANGELOG.md)
          if $(printf '%s' "$title" | grep -q ": "); then
            printf '%s - %s' "${{ env.RELEASE_VERSION }}" "${title#*: }" > title
          else
            printf '%s' "${{ env.RELEASE_VERSION }}" > title
          fi

      - name: Save release title
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: title
          if-no-files-found: error

      - name: Extract release changelog
        run: |
          begin=$(grep -nm1 "<\!--BEGIN=${{ env.RELEASE_VERSION }}-->" CHANGELOG.md | cut -d: -f1)
          end=$(grep -nm1 "<\!--END=${{ env.RELEASE_VERSION }}-->" CHANGELOG.md | cut -d: -f1)
          if [ -z "$begin" ] || [ -z "$end" ]; then
            echo 'Failed to find the release body tags for version ${{ env.RELEASE_VERSION }} in CHANGELOG.md.'
            exit 1
          fi
          sed -n "$((begin+1)),$((end-1))p" CHANGELOG.md > changelog.md

      - name: Save release changelog
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: changelog.md
          if-no-files-found: error

      - name: Strip changelog of release body tags
        run: sed -i 's/<!--BEGIN.*-->//g;s/<!--END.*-->//g' CHANGELOG.md

      - name: Save clean changelog
        uses: actions/upload-artifact@v2
        with:
          name: clean_changelog
          path: CHANGELOG.md
          if-no-files-found: error

  build-package:
    name: Create package
    needs: preparations
    env:
      RUST_BACKTRACE: 1
    strategy:
      matrix:
        build: [i686-unknown-linux-gnu, x86_64-unknown-linux-gnu, i686-pc-windows-msvc, x86_64-pc-windows-msvc]
        include:
          - build: i686-unknown-linux-gnu
            os: ubuntu-20.04
            toolchain: stable
            target: i686-unknown-linux-gnu
          - build: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            toolchain: stable
            target: x86_64-unknown-linux-gnu
          - build: i686-pc-windows-msvc
            os: windows-2019
            toolchain: stable
            target: i686-pc-windows-msvc
          - build: x86_64-pc-windows-msvc
            os: windows-2019
            toolchain: stable
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create release version env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libx11-xcb-dev:i386 gcc-multilib

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        shell: bash
        run: cargo build --verbose --release --target ${{ matrix.target }}

      - name: Load clean changelog
        uses: actions/download-artifact@v2
        with:
          name: clean_changelog

      - name: Package release
        shell: bash
        run: |
          staging="genrepass-${{ env.RELEASE_VERSION }}-${{ matrix.target }}"
          mkdir "$staging"
          mv README.md CHANGELOG.md LICENSE "$staging"
          if [ "${{ matrix.os }}" = "windows-2019" ]; then
            mv "target/${{ matrix.target }}/release/genrepass.exe" "$staging"
            7z a "$staging.zip" "$staging"
            echo "ASSET=$staging.zip" >> $GITHUB_ENV
          else
            mv "target/${{ matrix.target }}/release/genrepass" "$staging"
            tar czf "$staging.tar.gz" "$staging"
            echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          fi

      - name: Save package
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: ${{ env.ASSET }}
          if-no-files-found: error

  update-scoop-manifest:
    name: Update scoop manifest
    needs: build-package
    runs-on: ubuntu-20.04
    steps:
      - name: Create release version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Load packages and extras
        uses: actions/download-artifact@v2

      - name: Create sha256 file
        run: |
          cd packages
          sha256sum genrepass-* > genrepass-${{ env.RELEASE_VERSION }}.sha256

      - name: Save sha256
        uses: actions/upload-artifact@v2
        with:
          name: sha256
          path: packages/genrepass-${{ env.RELEASE_VERSION }}.sha256
          if-no-files-found: error

      - name: Update scoop manifest
        shell: bash
        run: |
          hash_64bit=$(grep x86_64-unknown-linux-gnu packages/genrepass-${{ env.RELEASE_VERSION }}.sha256 | cut -d ' ' -f1)
          hash_32bit=$(grep i686-unknown-linux-gnu packages/genrepass-${{ env.RELEASE_VERSION }}.sha256 | cut -d ' ' -f1)

          sed "s/REPLACE_VERSION/$RELEASE_VERSION/g;s/REPLACE_HASH_64BIT/$hash_64bit/;s/REPLACE_HASH_32BIT/$hash_32bit/" \
              genrepass-template.json > genrepass.json

      - name: Commit updated scoop manifest
        uses: EndBug/add-and-commit@v9
        with:
          add: 'genrepass.json'
          default_author: github_actions
          message: 'Update scoop manifest to `${{ env.RELEASE_VERSION }}`'

  create-release:
    name: Create release
    needs: update-scoop-manifest
    runs-on: ubuntu-20.04
    steps:
      - name: Load packages and extras
        uses: actions/download-artifact@v2
        
      - name: Create release title env
        run: echo "RELEASE_TITLE=$(cat release/title)" >> $GITHUB_ENV
        
      - name: Move sha256 file to packages
        run: mv sha256/genrepass-*.sha256 packages/

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_TITLE }}
          bodyFile: release/changelog.md
          artifacts: "packages/*"
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-crate:
    name: Publish crate
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Publish crate
        run: |
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cargo publish --no-verify

  publish-aur:
    name: Publish AUR package
    needs: create-release
    runs-on: ubuntu-20.04
    steps:
      - name: Create release version env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Load sha256 file
        uses: actions/download-artifact@v2
        with:
          name: sha256

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare PKGBUILD
        run: |
          sed -i "s/REPLACE_VERSION/${{ env.RELEASE_VERSION }}/" PKGBUILD
          
          sha256_x86_64=$(grep x86_64-unknown-linux-gnu genrepass-${{ env.RELEASE_VERSION }}.sha256 | cut -d ' ' -f1)
          sed -i "s/REPLACE_SHA256SUMS_X86_64/$sha256_x86_64/" PKGBUILD

          sha256_i686=$(grep i686-unknown-linux-gnu genrepass-${{ env.RELEASE_VERSION }}.sha256 | cut -d ' ' -f1)
          sed -i "s/REPLACE_SHA256SUMS_i686/$sha256_i686/" PKGBUILD

      - name: Publish to the AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: genrepass-bin
          pkgbuild: PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Release ${{ env.RELEASE_VERSION }}
